import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  documents: [{type: 'autogenerated', dirName: 'Documents'}],
  guides: [{type: 'autogenerated', dirName: 'Guides'}],
};

export default sidebars;
